### ISSUE TITLE
Beaver Builder modules and Translation Editor

### ISSUE THREAD

**Issue by andreasciamanna** [OnTheGoSystems/wpml-page-builders-beaver-builder#1]
Ref.: wpmlcore-5145

There are few modules that handle media files which are not properly parsed for translation in the Translation Editor.

In general, it's possible to translate the body of all "media block" (Picture, Video, Content Slider, Maps, Gallery, ...), but not the alt tag or other similar attributes.

You can add these Beaver Builder blocks, but when you try to translate the page/post from the Translation Editor you'll need to manually change, for instance, the alt tag in HTML.

![image](https://user-images.githubusercontent.com/181780/35554826-5cbecb96-059d-11e8-87ff-3a7c28a4b00c.png)

**Comment by andreasciamanna** [comment]
@OnTheGoSystems/wpml @OnTheGoSystems/compatibility

**Comment by vukvukovich** [comment]
Adding here updated list of modules not parsed for TE:

**Map** - Location
**Number counter** - Number Prefix and Suffix
**Posts** - More Link Text
**Posts Slider** - More Link Text
**Contact Form** - Name Field Placeholder, Subject Field Placeholder, Email Field Placeholder,  Phone Field Placeholder, Your Message Placeholder, Checkbox Text, Terms and Conditions
**Subscribe Form** - Notification Subject, Checkbox Text, Terms and Conditions

**Comment by vukvukovich** [comment]
Here is the PR #4.

**Comment by vukvukovich** [comment]
Fixed.
